#[cfg(feature = "browser_assets")]
pub mod browser_assets;
#[cfg(feature = "business_assets")]
pub mod business_assets;
#[cfg(feature = "communication_assets")]
pub mod communication_assets;
#[cfg(feature = "controller_assets")]
pub mod controller_assets;
#[cfg(feature = "dev_assets")]
pub mod dev_assets;
#[cfg(feature = "device_assets")]
pub mod device_assets;
#[cfg(feature = "editing_assets")]
pub mod editing_assets;
#[cfg(feature = "env_assets")]
pub mod env_assets;
#[cfg(feature = "file_assets")]
pub mod file_assets;
#[cfg(feature = "info_assets")]
pub mod info_assets;
#[cfg(feature = "multimedia_assets")]
pub mod multimedia_assets;
#[cfg(feature = "nav_assets")]
pub mod nav_assets;
#[cfg(feature = "object_assets")]
pub mod object_assets;
#[cfg(feature = "social_assets")]
pub mod social_assets;
#[cfg(feature = "ux_assets")]
pub mod ux_assets;
